project:
  type: website

website:
  title: "Stephen Feagin"
  site-url: "https://stephenfeagin.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - projects.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

