{
  "hash": "d3f90e7e924f217d95bc8cbd85a357dc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Confusing (Erroneous?) Data from the College Scorecard API\"\ndate: 2026-01-16\ncategories:\n  - r\n  - httr2\nexecute: \n  message: false\n  warning: false\n---\n\n\n\nI was playing with the [College Scorecard API](https://collegescorecard.ed.gov/data/api-documentation/)\nand encounted a confusing, and possibly erroneous, trend in the data. I was interested in examining the ranges of SAT scores of admitted students. I requested data for each of the three components (critical reading, math, and writing), for the 25th and 75th percentiles and the midpoint. I assumed that \"midpoint\" meant median, but maybe I'm wrong? Because when I pulled the data, I noticed that in several instances the 25th percentile was actually higher than the midpoint. I'll illustrate with an example.\n\nLet's pull down the data for my alma mater, UNC Chapel Hill. This is the request that I used:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(httr2)\nkey <- Sys.getenv(\"API_KEY\")\nbase_url <- paste0(\n  \"https://api.data.gov/ed/collegescorecard/v1/schools?api_key=\",\n  key\n)\n\nparameters <- paste0(\n  \"&id=199120\",\n  \"&fields=school.name,\",\n  \"latest.admissions.sat_scores.25th_percentile.critical_reading,\",\n  \"latest.admissions.sat_scores.midpoint.critical_reading,\",\n  \"latest.admissions.sat_scores.75th_percentile.critical_reading,\",\n  \"latest.admissions.sat_scores.25th_percentile.math,\",\n  \"latest.admissions.sat_scores.midpoint.math,\",\n  \"latest.admissions.sat_scores.75th_percentile.math,\",\n  \"latest.admissions.sat_scores.25th_percentile.writing,\",\n  \"latest.admissions.sat_scores.midpoint.writing,\",\n  \"latest.admissions.sat_scores.75th_percentile.writing\"\n)\n\nfinal_url <- paste0(\n  base_url, \n  parameters\n)\n\nreq <- request(final_url) |> \n  req_headers(\"Accept\" = \"application/json\")\n\nresp <- req_perform(req)\nbody <- resp_body_json(resp)\n```\n:::\n\n\n\nI don't want to ping the API every time I render my website, so I used `eval: false` in the above code block, and instead read from a CSV file I wrote out. We see the results below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- readr::read_csv(\"unc_sat_data.csv\")\nprint(t(results))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                              [,1]                                         \nlatest.admissions.sat_scores.25th_percentile.critical_reading \"680\"                                        \nlatest.admissions.sat_scores.midpoint.critical_reading        \"625\"                                        \nlatest.admissions.sat_scores.75th_percentile.critical_reading \"750\"                                        \nlatest.admissions.sat_scores.25th_percentile.math             \"690\"                                        \nlatest.admissions.sat_scores.midpoint.math                    \"635\"                                        \nlatest.admissions.sat_scores.75th_percentile.math             \"780\"                                        \nlatest.admissions.sat_scores.25th_percentile.writing          \"590\"                                        \nlatest.admissions.sat_scores.midpoint.writing                 \"645\"                                        \nlatest.admissions.sat_scores.75th_percentile.writing          \"700\"                                        \nschool.name                                                   \"University of North Carolina at Chapel Hill\"\n```\n\n\n:::\n:::\n\n\n\nAs you can see, `25th_percentile.critical_reading` is 680, while `midpoint.critical_reading` is 625. Similarly, `25th_percentile.math` is 690, while `midpoint.math` is 635. The results for writing make sense though.\n\nSo I'm not sure exactly what the issue is here. Maybe I'm misunderstanding the data, or maybe there's an error in the data. Either way, it makes it difficult to know how to proceed with this analysis.\n\nI found that it is possible to request `50th_percentile.critical_reading` and math and that returns sensible results. But when I request `50th_percentile.writing`, it doesn't give me an error but it doesn't respond that variable at all. Anyway, I'm finding this API frustrating.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}