{
  "hash": "d0a80eab982b82dc3d21b63759869af0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis of a Conjoint Survey Experiment\"\ndate: 2026-04-26\ncategories:\n  - r\n  - dplyr\n  - data science\nexecute: \n  message: false\n  warning: false\n---\n\n\n\nBelow is the analysis of a conjoint survey experiment that I performed for [Professor Mara Revkin](https://www.mararevkin.com/) at Duke University. \nI am not able to include the details of the survey experiment such as the text of the questions at this time. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages(library(lmtest))\nsuppressPackageStartupMessages(library(sandwich))\nsuppressPackageStartupMessages(library(tidyverse))\n```\n:::\n\n\n\n\nIn the questionnaire, this analysis covers chapter 10 questions 74-78. There 3 \niterations of the experimental treatment per respondent.\nThe relevant variables, where `x` is the iteration number 1-3:  \n\n* `I_x_Q_75` -- iteration x, randomization 1\n* `I_x_Q_76` -- iteration x, randomization 2\n* `I_x_Q_77` -- iteration x, randomization 3\n* `I_x_Q_78` -- iteration x, randomization 4\n* `I_x_Q6_4` -- iteration x, response 1\n* `I_x_Q6_5_A` -- iteration x, response 2\n\n## Data Wrangling\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read_csv(\"data/feb9data.csv\")\n```\n:::\n\n\n\nFor response variable 2, `Q6_5_A`, I am going to:\n\n* convert `-1` to `NA`\n* convert `2. No` to 0\n* convert `1. Yes` to 1\n\nI use `sapply()` to convert the responses for this variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconvert_q6_5a <- function(x) {\n  if (x == \"2. No\") return(0)\n  else if (x == \"1. Yes\") return(1)\n  else return(NA)\n}\n\ndf$I_1_Q6_5_A <- unname(sapply(df$I_1_Q6_5_A, convert_q6_5a))\ndf$I_2_Q6_5_A <- unname(sapply(df$I_2_Q6_5_A, convert_q6_5a))\ndf$I_3_Q6_5_A <- unname(sapply(df$I_3_Q6_5_A, convert_q6_5a))\n```\n:::\n\n\n\nI'm going to select the subset of columns that I want to actually do analysis\non, using *dplyr*'s `ends_with()` select helper:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_sub <- df |> \n  select(SbjNum,\n         ends_with(\"_Q_75\"),\n         ends_with(\"_Q_76\"),\n         ends_with(\"_Q_77\"),\n         ends_with(\"_Q_78\"),\n         ends_with(\"_Q6_4\"),\n         ends_with(\"_Q6_5_A\"))\n```\n:::\n\n\n\nNow we work on reshaping the data using `gather()`. I conduct a few QA checks to\nensure that the reshaping did not result in any data loss.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngathered_vars <- df_sub |> \n  select(SbjNum,\n         ends_with(\"_Q_75\"),\n         ends_with(\"_Q_76\"),\n         ends_with(\"_Q_77\"),\n         ends_with(\"_Q_78\")) |> \n  gather(variable, value, -SbjNum) \n\niterations <- as.numeric(\n  str_match(gathered_vars$variable, \"I_(\\\\d)_Q_7.\")[, 2]\n)\nq_num <- str_match(gathered_vars$variable, \"I_\\\\d_(Q_\\\\d{2})\")[, 2]\n```\n:::\n\n\n\nLet's look at `iterations` and `q_num` to make sure they have the right number of\nvalues and the correct distributions:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(iterations) == nrow(gathered_vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(q_num) == nrow(gathered_vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(iterations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\niterations\n   1    2    3 \n3004 3004 3004 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(q_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nq_num\nQ_75 Q_76 Q_77 Q_78 \n2253 2253 2253 2253 \n```\n\n\n:::\n:::\n\n\n\nOk, they all have the correct number of items all equally distributed. I now\ncreate a new data frame with the reshaped data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreshaped_vars <- cbind(gathered_vars, iterations, q_num) |> \n  select(-variable) |> \n  spread(q_num, value) |> \n  rename(iteration = iterations)\n```\n:::\n\n\n\nQuality assurance: Randomly select 5 subject IDs and confirm that the values are\nthe same between the original data frame and the gathered data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqa_subjects <- sample(gathered_vars$SbjNum, 5)\n\nfor (subject in qa_subjects) {\n  print(paste(\"Subject:\", subject))\n  df_subject_original <- filter(df_sub, SbjNum == subject)\n  df_subject_gathered <- filter(reshaped_vars, SbjNum == subject)\n  \n  for (iter in 1:3) {\n    # Q_75\n    gathered_75 <- df_subject_gathered |> \n      filter(iteration == iter) |> \n      select(Q_75) |> \n      pull()\n    print(paste(\n      \"Iteration\", \n      iter,\n      \"Q_75:\", \n      df_subject_original[[paste0(\"I_\", iter, \"_Q_75\")]] == gathered_75\n    ))\n    \n    # Q_76\n    gathered_76 <- df_subject_gathered |> \n      filter(iteration == iter) |> \n      select(Q_76) |> \n      pull()\n    print(paste(\n      \"Iteration\",\n      iter,\n      \"Q_76:\", \n      df_subject_original[[paste0(\"I_\", iter, \"_Q_76\")]] == gathered_76\n    ))\n    \n    # Q_77\n    gathered_77 <- df_subject_gathered |> \n      filter(iteration == iter) |> \n      select(Q_77) |> \n      pull()\n    print(paste(\n      \"Iteration\", \n      iter,\n      \"Q_77:\", \n      df_subject_original[[paste0(\"I_\", iter, \"_Q_77\")]] == gathered_77\n    ))\n    \n    # Q_78\n    gathered_78 <- df_subject_gathered |> \n      filter(iteration == iter) |> \n      select(Q_78) |> \n      pull()\n    print(paste(\n      \"Iteration\",\n      iter,\n      \"Q_78:\", \n      df_subject_original[[paste0(\"I_\", iter, \"_Q_78\")]] == gathered_78\n    ))\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Subject: 214973643\"\n[1] \"Iteration 1 Q_75: TRUE\"\n[1] \"Iteration 1 Q_76: TRUE\"\n[1] \"Iteration 1 Q_77: TRUE\"\n[1] \"Iteration 1 Q_78: TRUE\"\n[1] \"Iteration 2 Q_75: TRUE\"\n[1] \"Iteration 2 Q_76: TRUE\"\n[1] \"Iteration 2 Q_77: TRUE\"\n[1] \"Iteration 2 Q_78: TRUE\"\n[1] \"Iteration 3 Q_75: TRUE\"\n[1] \"Iteration 3 Q_76: TRUE\"\n[1] \"Iteration 3 Q_77: TRUE\"\n[1] \"Iteration 3 Q_78: TRUE\"\n[1] \"Subject: 214956718\"\n[1] \"Iteration 1 Q_75: TRUE\"\n[1] \"Iteration 1 Q_76: TRUE\"\n[1] \"Iteration 1 Q_77: TRUE\"\n[1] \"Iteration 1 Q_78: TRUE\"\n[1] \"Iteration 2 Q_75: TRUE\"\n[1] \"Iteration 2 Q_76: TRUE\"\n[1] \"Iteration 2 Q_77: TRUE\"\n[1] \"Iteration 2 Q_78: TRUE\"\n[1] \"Iteration 3 Q_75: TRUE\"\n[1] \"Iteration 3 Q_76: TRUE\"\n[1] \"Iteration 3 Q_77: TRUE\"\n[1] \"Iteration 3 Q_78: TRUE\"\n[1] \"Subject: 214697804\"\n[1] \"Iteration 1 Q_75: TRUE\"\n[1] \"Iteration 1 Q_76: TRUE\"\n[1] \"Iteration 1 Q_77: TRUE\"\n[1] \"Iteration 1 Q_78: TRUE\"\n[1] \"Iteration 2 Q_75: TRUE\"\n[1] \"Iteration 2 Q_76: TRUE\"\n[1] \"Iteration 2 Q_77: TRUE\"\n[1] \"Iteration 2 Q_78: TRUE\"\n[1] \"Iteration 3 Q_75: TRUE\"\n[1] \"Iteration 3 Q_76: TRUE\"\n[1] \"Iteration 3 Q_77: TRUE\"\n[1] \"Iteration 3 Q_78: TRUE\"\n[1] \"Subject: 214812854\"\n[1] \"Iteration 1 Q_75: TRUE\"\n[1] \"Iteration 1 Q_76: TRUE\"\n[1] \"Iteration 1 Q_77: TRUE\"\n[1] \"Iteration 1 Q_78: TRUE\"\n[1] \"Iteration 2 Q_75: TRUE\"\n[1] \"Iteration 2 Q_76: TRUE\"\n[1] \"Iteration 2 Q_77: TRUE\"\n[1] \"Iteration 2 Q_78: TRUE\"\n[1] \"Iteration 3 Q_75: TRUE\"\n[1] \"Iteration 3 Q_76: TRUE\"\n[1] \"Iteration 3 Q_77: TRUE\"\n[1] \"Iteration 3 Q_78: TRUE\"\n[1] \"Subject: 214912696\"\n[1] \"Iteration 1 Q_75: TRUE\"\n[1] \"Iteration 1 Q_76: TRUE\"\n[1] \"Iteration 1 Q_77: TRUE\"\n[1] \"Iteration 1 Q_78: TRUE\"\n[1] \"Iteration 2 Q_75: TRUE\"\n[1] \"Iteration 2 Q_76: TRUE\"\n[1] \"Iteration 2 Q_77: TRUE\"\n[1] \"Iteration 2 Q_78: TRUE\"\n[1] \"Iteration 3 Q_75: TRUE\"\n[1] \"Iteration 3 Q_76: TRUE\"\n[1] \"Iteration 3 Q_77: TRUE\"\n[1] \"Iteration 3 Q_78: TRUE\"\n```\n\n\n:::\n:::\n\n\nThat all looks good, I feel confident that the reshaping didn't mess up any of\nthe data points.\n\nNow I need to do the same kind of reshaping on the response variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngathered_responses <- df_sub |> \n  select(SbjNum,\n         matches(\"I_\\\\d_Q6_\\\\d*\")\n         ) |> \n  gather(variable, value, -SbjNum) \n\niterations <- as.numeric(\n  str_match(gathered_responses$variable, \"I_(\\\\d)_Q6\")[, 2]\n)\nq_num <- str_match(gathered_responses$variable, \"I_\\\\d_(Q6.+)\")[, 2]\n```\n:::\n\n\n\nEnsure correct number of items:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(iterations) == nrow(gathered_responses)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(q_num) == nrow(gathered_responses)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(iterations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\niterations\n   1    2    3 \n1502 1502 1502 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(q_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nq_num\n  Q6_4 Q6_5_A \n  2253   2253 \n```\n\n\n:::\n:::\n\n\n\nThat all looks good.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreshaped_responses <- cbind(gathered_responses, iterations, q_num) |> \n  select(-variable) |> \n  spread(q_num, value) |> \n  rename(iteration = iterations)\n```\n:::\n\n\n\nRepeat the same kind of QA for the response variables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqa_subjects <- sample(reshaped_responses$SbjNum, 5)\n\nfor (subject in qa_subjects) {\n  print(paste(\"Subject:\", subject))\n  df_subject_original <- filter(df_sub, SbjNum == subject)\n  df_subject_reshaped <- filter(reshaped_responses, SbjNum == subject)\n  \n  for (iter in 1:3) {\n    # Q6_4\n    reshaped_6_4 <- df_subject_reshaped |> \n      filter(iteration == iter) |> \n      select(Q6_4) |> \n      pull()\n    original_response <- df_subject_original[[paste0(\"I_\", iter, \"_Q6_4\")]]\n    if (is.na(original_response) && is.na(reshaped_64)) {\n      print(paste(\"Iteration\", iter, \"Q6_4:\", TRUE))\n    } else {\n      print(paste(\n        \"Iteration\",\n        iter,\n        \"Q6_4:\",\n        original_response == reshaped_6_4\n      ))\n    }\n    \n    # Q6_5_A\n    reshaped_6_5_A <- df_subject_reshaped |> \n      filter(iteration == iter) |> \n      select(Q6_5_A) |> \n      pull()\n    original_response <- df_subject_original[[paste0(\"I_\", iter, \"_Q6_5_A\")]]\n    if (is.na(original_response) && is.na(reshaped_6_5_A)) {\n      print(paste(\"Iteration\", iter, \"Q6_5_A:\", TRUE))\n    } else {\n      print(paste(\n        \"Iteration\",\n        iter, \n        \"Q6_5_A:\", \n        original_response == reshaped_6_5_A\n      ))\n    }\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Subject: 214814821\"\n[1] \"Iteration 1 Q6_4: TRUE\"\n[1] \"Iteration 1 Q6_5_A: TRUE\"\n[1] \"Iteration 2 Q6_4: TRUE\"\n[1] \"Iteration 2 Q6_5_A: TRUE\"\n[1] \"Iteration 3 Q6_4: TRUE\"\n[1] \"Iteration 3 Q6_5_A: TRUE\"\n[1] \"Subject: 214976358\"\n[1] \"Iteration 1 Q6_4: TRUE\"\n[1] \"Iteration 1 Q6_5_A: TRUE\"\n[1] \"Iteration 2 Q6_4: TRUE\"\n[1] \"Iteration 2 Q6_5_A: TRUE\"\n[1] \"Iteration 3 Q6_4: TRUE\"\n[1] \"Iteration 3 Q6_5_A: TRUE\"\n[1] \"Subject: 215077674\"\n[1] \"Iteration 1 Q6_4: TRUE\"\n[1] \"Iteration 1 Q6_5_A: TRUE\"\n[1] \"Iteration 2 Q6_4: TRUE\"\n[1] \"Iteration 2 Q6_5_A: TRUE\"\n[1] \"Iteration 3 Q6_4: TRUE\"\n[1] \"Iteration 3 Q6_5_A: TRUE\"\n[1] \"Subject: 214937573\"\n[1] \"Iteration 1 Q6_4: TRUE\"\n[1] \"Iteration 1 Q6_5_A: TRUE\"\n[1] \"Iteration 2 Q6_4: TRUE\"\n[1] \"Iteration 2 Q6_5_A: TRUE\"\n[1] \"Iteration 3 Q6_4: TRUE\"\n[1] \"Iteration 3 Q6_5_A: TRUE\"\n[1] \"Subject: 214735734\"\n[1] \"Iteration 1 Q6_4: TRUE\"\n[1] \"Iteration 1 Q6_5_A: TRUE\"\n[1] \"Iteration 2 Q6_4: TRUE\"\n[1] \"Iteration 2 Q6_5_A: TRUE\"\n[1] \"Iteration 3 Q6_4: TRUE\"\n[1] \"Iteration 3 Q6_5_A: TRUE\"\n```\n\n\n:::\n:::\n\n\n\nAll looks good with the response reshaping.\n\nNow we can join the two data frames back together:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoined <- left_join(\n  reshaped_vars,\n  reshaped_responses,\n  by = c(\"SbjNum\", \"iteration\")\n)\n```\n:::\n\n\n\nI will now convert the randomization variables and Q6_4 to factor, and Q6_5_A to\nnumeric.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoined <- joined |> \n  mutate(\n    across(contains(\"Q_7\"), ~ factor(.x)),\n    Q6_4 =  factor(Q6_4,\n                   levels = c(\n                     \"1. Fully sufficient\",\n                     \"2. Somewhat sufficient\",\n                     \"3. Somewhat insufficient but better than nothing\",\n                     \"4. Totally insufficient\"\n                   ),\n                   labels = c(\n                     \"1. Fully sufficient\",\n                     \"2. Somewhat sufficient\",\n                     \"3. Somewhat insufficient\",\n                     \"4. Totally insufficient\"\n                   ),\n                   ordered = TRUE),\n    Q6_5_A = as.numeric(Q6_5_A)\n )\n```\n:::\n\n\n\nI like to make a \"final copy\" of the data after I'm done.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncleaned_data <- joined\n```\n:::\n\n\n\n\n## Analysis\n\nI think I can now run a couple basic analyses.\nFirst let's look at the distribution of response variables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(cleaned_data$Q6_4, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     1. Fully sufficient   2. Somewhat sufficient 3. Somewhat insufficient \n                     473                      525                      443 \n 4. Totally insufficient                     <NA> \n                     810                        2 \n```\n\n\n:::\n:::\n\n\n\nA plurality of respondents answered \"4. Totally insufficient\", with the other\noptions quite a bit lower.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(cleaned_data$Q6_5_A, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 <NA> \n 680  917  656 \n```\n\n\n:::\n:::\n\n\n\nYes has more responses than No, but there are a large number of NAs.\n\n## Ordered logit without respondent effects\n\nI will now look at an ordered logit regression for Q6_4.\nThis model does not control for subject.\n\nPlease note, due to the length of the response values the tables below are\nextremely wide. You can scroll side to side to show the point estimates and\nother relevant statistics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq6_4_logit <- MASS::polr(Q6_4 ~ Q_75 + Q_76 + Q_77 + Q_78, \n                         data = cleaned_data, \n                         method = \"logistic\",\n                         Hess = TRUE)\n\n# Compute Odds Ratios and Confidence Intervals\nexp(cbind(OR = coef(q6_4_logit), confint(q6_4_logit)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                                                                                    OR\nQ_75We would like to apologize for the death of your loved one.                                                              0.8823071\nQ_75We would like to express our sympathy for the death of your loved one.                                                   0.9535238\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                             0.7707824\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            0.3205635\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to 0.8578855\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force 0.8303470\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul  0.7134516\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf   0.6427085\n                                                                                                                                 2.5 %\nQ_75We would like to apologize for the death of your loved one.                                                              0.7361427\nQ_75We would like to express our sympathy for the death of your loved one.                                                   0.7896712\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                             0.6365587\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            0.2658655\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to 0.7127676\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force 0.6896368\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul  0.5939732\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf   0.5330191\n                                                                                                                                97.5 %\nQ_75We would like to apologize for the death of your loved one.                                                              1.0573268\nQ_75We would like to express our sympathy for the death of your loved one.                                                   1.1513703\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                             0.9330271\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            0.3860622\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to 1.0323678\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force 0.9995685\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul  0.8566594\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf   0.7746367\n```\n\n\n:::\n:::\n\n\n\nIt looks like Q75, the messaging around the loss, doesn't contain significant\neffects across feature levels at the 0.05 level.\n\nNote that Q6_4 is ordered such that lower values indicate greater sufficiency.\nI can reverse that if we want.\nSo in looking at the data, an odds ratio below 1 indicates a higher degree of\nsufficiency.\n\nThere are a number of feature levels where the confidence interval does not\ncontain 1:\n- Q76: One-time payment of 3 million Dinars: OR 0.771\n- Q76: One-time payment of 30 million Dinars: OR 0.321\n- Q77: No evidence of wrongdoing: 0.830\n- Q78: Public memorial: 0.713\n- Q78: New schools: 0.643\n\nI can cluster standard errors by respondent using the *sandwich* package:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoeftest(q6_4_logit, vcov = vcovCL(q6_4_logit, cluster = ~ SbjNum))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                                                                                                                              Estimate\nQ_75We would like to apologize for the death of your loved one.                                                              -0.125215\nQ_75We would like to express our sympathy for the death of your loved one.                                                   -0.047591\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                             -0.260349\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            -1.137675\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to -0.153285\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force -0.185912\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul  -0.337641\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf   -0.442064\n                                                                                                                             Std. Error\nQ_75We would like to apologize for the death of your loved one.                                                                0.092036\nQ_75We would like to express our sympathy for the death of your loved one.                                                     0.098503\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                               0.104934\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                              0.108773\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to   0.094921\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force   0.096449\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul    0.094216\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf     0.099666\n                                                                                                                              t value\nQ_75We would like to apologize for the death of your loved one.                                                               -1.3605\nQ_75We would like to express our sympathy for the death of your loved one.                                                    -0.4831\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                              -2.4811\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            -10.4591\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to  -1.6149\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  -1.9276\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   -3.5837\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf    -4.4355\n                                                                                                                              Pr(>|t|)\nQ_75We would like to apologize for the death of your loved one.                                                               0.173809\nQ_75We would like to express our sympathy for the death of your loved one.                                                    0.629041\nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                              0.013172\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            < 2.2e-16\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to  0.106481\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  0.054036\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   0.000346\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf   9.632e-06\n                                                                                                                                \nQ_75We would like to apologize for the death of your loved one.                                                                 \nQ_75We would like to express our sympathy for the death of your loved one.                                                      \nQ_76We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.                             *  \nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            ***\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to    \nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force .  \nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul  ***\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf   ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nWith the clustered standard errors, we still see significant results at the 0.05 \nlevel for:\n- Q76: 3 million Dinars\n- Q76: 30 million Dinars\n- Q78: Public memorial\n- Q78: New schools\nNote that Q77: no evidence of wrongdoing is close to p < 0.05.\n\n## Binary logit for Q6_5_A\n\nWould the respondent accept the offer of compensation?\n\nFirst, exclude randomizations that do not include compensation, and re-label the\nfactor\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompensation_rows <- cleaned_data |> \n  filter(Q_76 != \"Unfortunately, we cannot offer you any monetary compensation for your loss.\") |> \n  mutate(Q_76 = factor(\n    Q_76,\n    levels = c(\n      \"We can offer you a one-time payment of 3 million Iraqi Dinars as compensation for your loss.\",\n      \"We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.\"\n      )\n    )\n    )\n\nq6_5_a_logit <- glm(Q6_5_A ~ Q_75 + Q_76 + Q_77 + Q_78, \n                    data = compensation_rows,\n                    family = binomial(link = \"logit\"))\nsummary(q6_5_a_logit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Q6_5_A ~ Q_75 + Q_76 + Q_77 + Q_78, family = binomial(link = \"logit\"), \n    data = compensation_rows)\n\nCoefficients:\n                                                                                                                             Estimate\n(Intercept)                                                                                                                  -0.54051\nQ_75We would like to apologize for the death of your loved one.                                                               0.13688\nQ_75We would like to express our sympathy for the death of your loved one.                                                    0.04118\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                             1.25561\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to -0.18102\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  0.03259\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   0.16550\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf    0.04471\n                                                                                                                             Std. Error\n(Intercept)                                                                                                                     0.15403\nQ_75We would like to apologize for the death of your loved one.                                                                 0.13065\nQ_75We would like to express our sympathy for the death of your loved one.                                                      0.13543\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                               0.10915\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to    0.13373\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force    0.13382\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul     0.13157\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf      0.13388\n                                                                                                                             z value\n(Intercept)                                                                                                                   -3.509\nQ_75We would like to apologize for the death of your loved one.                                                                1.048\nQ_75We would like to express our sympathy for the death of your loved one.                                                     0.304\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                             11.504\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to  -1.354\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force   0.244\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul    1.258\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf     0.334\n                                                                                                                             Pr(>|z|)\n(Intercept)                                                                                                                   0.00045\nQ_75We would like to apologize for the death of your loved one.                                                               0.29479\nQ_75We would like to express our sympathy for the death of your loved one.                                                    0.76105\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                             < 2e-16\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to  0.17586\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  0.80758\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   0.20842\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf    0.73842\n                                                                                                                                \n(Intercept)                                                                                                                  ***\nQ_75We would like to apologize for the death of your loved one.                                                                 \nQ_75We would like to express our sympathy for the death of your loved one.                                                      \nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            ***\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to    \nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force    \nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul     \nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2071.2  on 1503  degrees of freedom\nResidual deviance: 1927.9  on 1496  degrees of freedom\nAIC: 1943.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\nClustered SEs:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoeftest(q6_5_a_logit, vcov = vcovCL(q6_5_a_logit, cluster = ~ SbjNum))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n                                                                                                                              Estimate\n(Intercept)                                                                                                                  -0.540512\nQ_75We would like to apologize for the death of your loved one.                                                               0.136876\nQ_75We would like to express our sympathy for the death of your loved one.                                                    0.041184\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                             1.255610\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to -0.181020\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  0.032593\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   0.165501\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf    0.044710\n                                                                                                                             Std. Error\n(Intercept)                                                                                                                    0.166567\nQ_75We would like to apologize for the death of your loved one.                                                                0.127339\nQ_75We would like to express our sympathy for the death of your loved one.                                                     0.135198\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                              0.121705\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to   0.136601\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force   0.137889\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul    0.133064\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf     0.134176\n                                                                                                                             z value\n(Intercept)                                                                                                                  -3.2450\nQ_75We would like to apologize for the death of your loved one.                                                               1.0749\nQ_75We would like to express our sympathy for the death of your loved one.                                                    0.3046\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            10.3169\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to -1.3252\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  0.2364\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   1.2438\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf    0.3332\n                                                                                                                              Pr(>|z|)\n(Intercept)                                                                                                                   0.001174\nQ_75We would like to apologize for the death of your loved one.                                                               0.282424\nQ_75We would like to express our sympathy for the death of your loved one.                                                    0.760654\nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            < 2.2e-16\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to  0.185115\nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force  0.813148\nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul   0.213587\nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf    0.738969\n                                                                                                                                \n(Intercept)                                                                                                                  ** \nQ_75We would like to apologize for the death of your loved one.                                                                 \nQ_75We would like to express our sympathy for the death of your loved one.                                                      \nQ_76We can offer you a one-time payment of 30 million Iraqi Dinars as compensation for your loss.                            ***\nQ_77We would like to assure you that we have incorporated the lessons learned from your case into our training curriculum to    \nQ_77We would like to assure you that we thoroughly investigated your case and found no evidence of wrongdoing by Iraqi force    \nQ_78The Iraqi government has agreed to build a public memorial to commemorate the victims of Daesh and the battle for Mosul     \nQ_78The Iraqi government has agreed to build three new schools in Mosul to support the city’s recovery from the losses suf      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nFor this binary response, the only significant effect is the 30 million Dinars.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}